# Generated by Django 3.1.1 on 2020-11-16 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201116_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='products.ingredient'),
        ),
    ]
