version: '3.8'

volumes:
  postgres_data:
  static1:

services:
  db:
    image: postgres:12.4
    volumes:
#      - postgres_data:/var/lib/postgresql/data/
       - ./data:/data
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    command: sh -c "python manage.py migrate --noinput && python manage.py loaddata data/tags.json && python manage.py loaddata data/ingredients.json  && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static1:/var/www/web/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static1:/var/www/nginx/static
    ports:
      - "81:80"
    depends_on:
      - web